services:
  - type: web
    name: my-django-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn my_project.wsgi
    envVars:
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@example.com
      - key: DJANGO_SUPERUSER_PASSWORD
        value: supersecurepassword
